"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env Acrobot-v1
pause
