"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
"C:\Anaconda3\envs\torch\python.exe" "C:\repository\drl\dqn_examples.py" --env MountainCar-v0
pause
